name: Fruit Stock Management

on:
  push:
    branches:
      - main

jobs:
  build:
    name: 🏗️ Build Application
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Install Task
        uses: arduino/setup-task@v2

      - name: Install JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '22'
          cache: maven
      
      - name: Build Application
        env:
          MAVEN_CLI_OPTS: >-
            --no-transfer-progress 
            --errors 
            --fail-at-end
            --show-version 
            --batch-mode
          MAVEN_OPTS: >-
            -Djansi.force=true
            -Dstyle.color=always 
        run: |
          task build-app
    
      - name: Scan SBOM
        uses: anchore/scan-action@v3
        with:
          sbom: target/sbom.json
          fail-build: false
          output-format: table
          by-cve: true

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: fruit-stock-management
          path: target/fruit-stock-management-*.jar
          retention-days: 30
  
  conatiner-image:
    name: 🏭 Build Container Image
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    needs: 
      - build
    if: ${{ success() }}
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Download Artefact
        uses: actions/download-artifact@v4
        with:
          name: fruit-stock-management
          path: target
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            type=ref,event=branch
      
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v5
        with:
          context: ./
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:build-cache
          # This cache storage backend is not supported with the default "docker" BuildX driver
          # https://docs.docker.com/build/drivers/
          # The buildX setup creates and uses a builder based on the “docker-container” driver (https://docs.docker.com/build/drivers/docker-container/). 
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:build-cache,mode=max
      
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
      

  